# This is a basic workflow to help you get started with Actions

name: Build app on PR

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
  workflow_dispatch:  # Allows manual trigger from GitHub UI

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: echo "@infragistics:registry=https://packages.infragistics.com/npm/js-licensed/" >> ~/.npmrc
      - run: echo "//packages.infragistics.com/npm/js-licensed/:_auth=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc
      - run: echo "//packages.infragistics.com/npm/js-licensed/:always-auth=true" >> ~/.npmrc
      - name: Clean dist and docs
        run: |
          rm -rf dist
          rm -rf docs

      - name: Install dependencies
        run: npm ci

      - name: Replace environment variables
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
        run: |
          chmod +x scripts/replace-env-vars.sh
          echo "=== DEBUG: Printing environment variables before replacement ==="
          echo "FIREBASE_API_KEY: $FIREBASE_API_KEY"
          echo "FIREBASE_AUTH_DOMAIN: $FIREBASE_AUTH_DOMAIN"
          echo "FIREBASE_DATABASE_URL: $FIREBASE_DATABASE_URL"
          echo "FIREBASE_PROJECT_ID: $FIREBASE_PROJECT_ID"
          echo "FIREBASE_STORAGE_BUCKET: $FIREBASE_STORAGE_BUCKET"
          echo "FIREBASE_MESSAGING_SENDER_ID: $FIREBASE_MESSAGING_SENDER_ID"
          echo "==============================================================="
          ./scripts/replace-env-vars.sh
          echo "=== AFTER REPLACEMENT ==="
          cat src/environments/environment.prod.ts

      - name: Debug env file contents
        run: |
          echo "=== DEBUG: Contents of environment.prod.ts after replacement ==="
          cat src/environments/environment.prod.ts
          echo "================================================================"

      - name: Run lint
        run: npm run lint

      - name: Build Angular app
        run: npm run build