# Build & Deploy Angular App to GitHub Pages
name: Build and Deploy App

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Configure private npm registry
        run: |
          echo "@infragistics:registry=https://packages.infragistics.com/npm/js-licensed/" >> ~/.npmrc
          echo "//packages.infragistics.com/npm/js-licensed/:_auth=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc
          echo "//packages.infragistics.com/npm/js-licensed/:always-auth=true" >> ~/.npmrc

      - name: Clean dist and docs
        run: |
          rm -rf dist
          rm -rf docs

      - name: Install dependencies
        run: npm ci

      - name: Replace Firebase environment variables
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
        run: |
          chmod +x scripts/replace-env-vars.sh
          ./scripts/replace-env-vars.sh
          echo "=== AFTER REPLACEMENT ==="
          cat src/environments/environment.prod.ts

      - name: Run lint
        run: npm run lint

      - name: Build Angular app
        run: npm run build:gh-pages   # produces dist/ folder

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist/browser

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
